title: "Lead Shift"
description: "Insights on engineering leadership, change, and transformation."
baseurl: "" # adjust if using a subpath
url: "https://<your-username>.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:year/:month/:day/:title/
