# Minimal Configuration for GitHub Pages
title: Lead Shift
description: Insights on engineering leadership, change, and transformation.
baseurl: "" # leave empty if hosted at username.github.io/repo-name
url: "https://wsaruman.github.io" # replace with your GitHub Pages URL

# Theme setup for GitHub Pages
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Optional for drafts
show_drafts: true # enable only in dev environment if using drafts

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
